words = [
    "asize",
    "bstr",
    "cbor",
    "cumasize",
    "cumdsize",
    "gid",
    "hardlink",
    "itemref",
    "kernfs",
    "ncdu",
    "nint",
    "nlink",
    "rderr",
    "shrasize",
    "shrdsize",
    "ustr",
    "xbf",
]
