# SPDX-FileCopyrightText: © 2026 Olivier Delrée <olivierdelree@protonmail.com>
#
# SPDX-License-Identifier: MIT

# ruff: noqa: E501

"""CBOR parsing limited to NCDU exports."""

import enum
import itertools
from typing import TYPE_CHECKING

from ncdu_reader.errors import CBORError

if TYPE_CHECKING:
    from collections.abc import Iterator

type CBORMap = dict[int, bool | int | str]


# fmt: off
class CBORBytes(enum.IntEnum):
    """Initial bytes of CBOR objects.

    This is not exhaustive as it only covers data that can be generated by NCDU.

    References:
        https://www.rfc-editor.org/rfc/rfc8949.html#section-appendix.b
    """

    UINT_START = 0x00  # unsigned integer 0x00..0x17 (0..23)
    UINT_END = 0x17  # unsigned integer 0x00..0x17 (0..23)
    UINT_ONE_BYTE = 0x18  # unsigned integer (one-byte uint8_t follows)
    UINT_TWO_BYTE = 0x19  # unsigned integer (two-byte uint16_t follows)
    UINT_FOUR_BYTE = 0x1A  # unsigned integer (four-byte uint32_t follows)
    UINT_EIGHT_BYTE = 0x1B  # unsigned integer (eight-byte uint64_t follows)
    NINT_START = 0x20  # negative integer -1-0x00..-1-0x17 (-1..-24)
    NINT_END = 0x37  # negative integer -1-0x00..-1-0x17 (-1..-24)
    NINT_ONE_BYTE = 0x38  # negative integer -1-n (one-byte uint8_t for n follows)
    NINT_TWO_BYTE = 0x39  # negative integer -1-n (two-byte uint16_t for n follows)
    NINT_FOUR_BYTE = 0x3A  # negative integer -1-n (four-byte uint32_t for n follows)
    NINT_EIGHT_BYTE = 0x3B  # negative integer -1-n (eight-byte uint64_t for n follows)
    BSTR_START = 0x40  # byte string (0x00..0x17 bytes follow)
    BSTR_END = 0x57  # byte string (0x00..0x17 bytes follow)
    BSTR_ONE_BYTE = 0x58  # byte string (one-byte uint8_t for n, and then n bytes follow)
    BSTR_TWO_BYTE = 0x59  # byte string (two-byte uint16_t for n, and then n bytes follow)
    BSTR_FOUR_BYTE = 0x5A  # byte string (four-byte uint32_t for n, and then n bytes follow)
    BSTR_EIGHT_BYTE = 0x5B  # byte string (eight-byte uint64_t for n, and then n bytes follow)
    USTR_START = 0x60  # UTF-8 string (0x00..0x17 bytes follow)
    USTR_END = 0x77  # UTF-8 string (0x00..0x17 bytes follow)
    USTR_ONE_BYTE = 0x78  # UTF-8 string (one-byte uint8_t for n, and then n bytes follow)
    USTR_TWO_BYTE = 0x79  # UTF-8 string (two-byte uint16_t for n, and then n bytes follow)
    USTR_FOUR_BYTE = 0x7A  # UTF-8 string (four-byte uint32_t for n, and then n bytes follow)
    USTR_EIGHT_BYTE = 0x7B  # UTF-8 string (eight-byte uint64_t for n, and then n bytes follow)
    MAP_INDEFINITE = 0xBF  # map, pairs of data items follow, terminated by "break"
    FALSE = 0xF4  # false
    TRUE = 0xF5  # true
    BREAK = 0xFF  # "break" stop code
# fmt: on


def read_cbor(raw: Iterator[int]) -> CBORMap:
    """Read a CBOR map from an iterator.

    Args:
        raw: Iterator over CBOR bytes.

    Returns:
        The result of parsing the iterator indefinite map.

    Raises:
        CBORError: Data ends unexpectedly.
        CBORError: Data is not a map.
        CBORError: Data type is not supported by this CBOR subset.
    """
    initial = next(raw)
    if initial != CBORBytes.MAP_INDEFINITE:
        raise CBORError("CBOR data should be a map.")

    map_: CBORMap = {}
    while (key := next(raw, None)) is not None:
        if key == CBORBytes.BREAK:
            break

        match initial := next(raw):
            case x if x in range(CBORBytes.UINT_START, CBORBytes.UINT_END + 1):
                value = initial
            case CBORBytes.UINT_ONE_BYTE:
                value = next(raw)
            case CBORBytes.UINT_TWO_BYTE:
                value = int.from_bytes(itertools.islice(raw, 2))
            case CBORBytes.UINT_FOUR_BYTE:
                value = int.from_bytes(itertools.islice(raw, 4))
            case CBORBytes.UINT_EIGHT_BYTE:
                value = int.from_bytes(itertools.islice(raw, 8))
            case x if x in range(CBORBytes.NINT_START, CBORBytes.NINT_END + 1):
                value = -1 - (initial & 0x1F)
            case CBORBytes.NINT_ONE_BYTE:
                value = -1 - next(raw)
            case CBORBytes.NINT_TWO_BYTE:
                value = -1 - int.from_bytes(itertools.islice(raw, 2))
            case CBORBytes.NINT_FOUR_BYTE:
                value = -1 - int.from_bytes(itertools.islice(raw, 4))
            case CBORBytes.NINT_EIGHT_BYTE:
                value = -1 - int.from_bytes(itertools.islice(raw, 8))
            case x if x in range(CBORBytes.BSTR_START, CBORBytes.BSTR_END + 1):
                value = "".join(map(chr, itertools.islice(raw, initial & 0x1F)))
            case CBORBytes.BSTR_ONE_BYTE:
                value = "".join(map(chr, itertools.islice(raw, next(raw))))
            case CBORBytes.BSTR_TWO_BYTE:
                length = int.from_bytes(itertools.islice(raw, 2))
                value = "".join(map(chr, itertools.islice(raw, length)))
            case CBORBytes.BSTR_FOUR_BYTE:
                length = int.from_bytes(itertools.islice(raw, 4))
                value = "".join(map(chr, itertools.islice(raw, length)))
            case CBORBytes.BSTR_EIGHT_BYTE:
                length = int.from_bytes(itertools.islice(raw, 8))
                value = "".join(map(chr, itertools.islice(raw, length)))
            case x if x in range(CBORBytes.USTR_START, CBORBytes.USTR_END + 1):
                value = bytes(itertools.islice(raw, initial & 0x1F)).decode("UTF-8")
            case CBORBytes.USTR_ONE_BYTE:
                value = bytes(itertools.islice(raw, next(raw) & 0x1F)).decode("UTF-8")
            case CBORBytes.USTR_TWO_BYTE:
                length = int.from_bytes(itertools.islice(raw, 2))
                value = bytes(itertools.islice(raw, length & 0x1F)).decode("UTF-8")
            case CBORBytes.USTR_FOUR_BYTE:
                length = int.from_bytes(itertools.islice(raw, 4))
                value = bytes(itertools.islice(raw, length & 0x1F)).decode("UTF-8")
            case CBORBytes.USTR_EIGHT_BYTE:
                length = int.from_bytes(itertools.islice(raw, 8))
                value = bytes(itertools.islice(raw, length & 0x1F)).decode("UTF-8")
            case CBORBytes.FALSE:
                value = False
            case CBORBytes.TRUE:
                value = True
            case CBORBytes.BREAK:
                raise CBORError("Unexpected break.")
            case _:
                raise CBORError(f"Unsupported initial byte '0x{initial:X}'.")

        map_[key] = value

    return map_
