# SPDX-FileCopyrightText: © 2026 Olivier Delrée <olivierdelree@protonmail.com>
#
# SPDX-License-Identifier: MIT

"""NCDU parsing from binary exports."""

import abc
import enum
import os
import pathlib
from compression import zstd
from dataclasses import dataclass
from typing import TYPE_CHECKING
from typing import BinaryIO
from typing import cast

from ncdu_reader.cbor import read_cbor
from ncdu_reader.errors import NCDUError
from ncdu_reader.errors import ParsingError

if TYPE_CHECKING:
    from ncdu_reader.cbor import CBORMap

NCDU_MAGIC_BYTES: bytes = b"\xbf\x6e\x63\x64\x75\x45\x58\x31"
"""Magic bytes for binary files generated by NCDU.

References:
    Magic bytes: https://dev.yorhel.nl/ncdu/binfmt#file-signature
"""

type ReferenceType = AbsoluteReference | RelativeReference


class ItemField(enum.IntEnum):
    """NCDU item fields found in CBOR data.

    References:
        Item types: https://dev.yorhel.nl/ncdu/binfmt#item
    """

    TYPE = 0
    NAME = 1
    PREV = 2
    ASIZE = 3
    DSIZE = 4
    DEV = 5
    RDERR = 6
    CUMASIZE = 7
    CUMDSIZE = 8
    SHRASIZE = 9
    SHRDSIZE = 10
    ITEMS = 11
    SUB = 12
    INO = 13
    NLINK = 14
    UID = 15
    GID = 16
    MODE = 17
    MTIME = 18


class ItemType(enum.IntEnum):
    """NCDU item type found in CBOR data.

    References:
        Item types: https://dev.yorhel.nl/ncdu/binfmt#item
    """

    ExcludedWithKernFS = -4
    ExcludeWithX = -3
    ExcludedByPattern = -2
    ErrorWhileReadingEntry = -1
    Directory = 0
    File = 1
    NonRegularFile = 2
    Hardlink = 3


@dataclass
class Block:
    """Generic NCDU block.

    References:
        Block format: https://dev.yorhel.nl/ncdu/binfmt#block-format
    """

    type: int
    length: int
    content: bytes


@dataclass
class DataBlock:
    """Data block containing file system information.

    References:
        Data block format: https://dev.yorhel.nl/ncdu/binfmt#data-blocks
    """

    index: int
    data: bytes

    @staticmethod
    def from_bytes(bytes_: bytes) -> DataBlock:
        """Parse a data block from bytes.

        Args:
            bytes_: Bytes containing block data.

        Returns:
            A data block parsed from the given bytes.
        """
        index = int.from_bytes(bytes_[:4], byteorder="big", signed=False)
        data = zstd.decompress(bytes_[4:])

        return DataBlock(index=index, data=data)


@dataclass
class IndexBlock:
    """Index block containing export pointers and references.

    References:
        Index block format: https://dev.yorhel.nl/ncdu/binfmt#index-block
    """

    pointers: list[BlockPointer]
    root_reference: AbsoluteReference

    @staticmethod
    def from_bytes(bytes_: bytes) -> IndexBlock:
        """Parse an index block from bytes.

        Args:
            bytes_: Bytes containing block data.

        Returns:
            An index block parsed from the given bytes.
        """
        pointers: list[BlockPointer] = []

        index = 0
        while index < len(bytes_):
            pointer = BlockPointer.from_int(
                int.from_bytes(bytes_[index : index + 8], byteorder="big", signed=False)
            )
            pointers.append(pointer)
            index += 8

        root_itemref = AbsoluteReference.from_int(pointers.pop().to_int())

        return IndexBlock(pointers=pointers, root_reference=root_itemref)


@dataclass
class AbsoluteReference:
    """Absolute item reference from the start of a block.

    References:
        https://dev.yorhel.nl/ncdu/binfmt#itemref
    """

    block_index: int
    offset: int

    @staticmethod
    def from_int(data: int) -> AbsoluteReference:
        """Parse an absolute itemref from an integer.

        Args:
            data: Integer to parse.

        Returns:
            A parsed absolute itemref.
        """
        block_index = data >> 24  # High 40 bits
        offset = data & ((0b1 << 24) - 1)  # Low 24 bits

        return AbsoluteReference(block_index=block_index, offset=offset)


@dataclass
class RelativeReference:
    """Relative item reference from the start of the item containing the reference.

    This is just a wrapper around a negative integer.

    References:
        https://dev.yorhel.nl/ncdu/binfmt#itemref
    """

    offset: int

    @staticmethod
    def from_int(data: int) -> RelativeReference:
        """Parse a relative itemref from an integer.

        Args:
            data: Integer to parse.

        Returns:
            A parsed relative itemref.
        """
        return RelativeReference(offset=data)


@dataclass
class BlockPointer:
    """Pointer to data blocks.

    Reference:
        https://dev.yorhel.nl/ncdu/binfmt#index-block
    """

    offset: int
    length: int

    def to_int(self) -> int:
        """Convert the pointer to an 8-byte integer.

        Returns:
            An 8-byte integer representation of the pointer.
        """
        return (self.offset << 24) | self.length

    @staticmethod
    def from_int(raw: int) -> BlockPointer:
        """Parse a pointer from an 8-byte integer.

        Args:
            raw: Raw integer.

        Returns:
            A parsed block pointer.
        """
        offset = raw >> 24  # High 40 bits
        length = raw & ((0b1 << 24) - 1)  # Lower 24 bits

        return BlockPointer(offset=offset, length=length)


@dataclass
class AnyItem(abc.ABC):
    """Common fields to all the entries in an export.

    References:
        Item fields: https://dev.yorhel.nl/ncdu/binfmt#item
    """

    reference: AbsoluteReference

    name: str
    type: int
    prev: ReferenceType | None = None


@dataclass
class ExcludedWithKernFS(AnyItem):
    """Item excluded with the --exclude-kernfs CLI flag."""

    type: int = ItemType.ExcludedWithKernFS


@dataclass
class ExcludedWithX(AnyItem):
    """Item excluded with the -x CLI flag."""

    type: int = ItemType.ExcludeWithX


@dataclass
class ExcludedByPattern(AnyItem):
    """Item excluded with pattern matching options."""

    type: int = ItemType.ExcludedByPattern


@dataclass
class ErrorWhileReadingEntry(AnyItem):
    """Item excluded because an error occurred while traversing the file system."""

    type: int = ItemType.ErrorWhileReadingEntry


@dataclass
class AnyIncludedItem(AnyItem, abc.ABC):
    """Abstract base class for all items that were not excluded for an export."""

    asize: int = 0
    dsize: int = 0
    uid: int | None = None
    gid: int | None = None
    mode: int | None = None
    mtime: int | None = None


@dataclass
class Directory(AnyIncludedItem):
    """Directory item in an NCDU export."""

    type: int = ItemType.Directory

    dev: int = 0
    rderr: bool | None = None
    cumasize: int = 0
    cumdsize: int = 0
    shrasize: int = 0
    shrdsize: int = 0
    items: int = 0
    sub: ReferenceType | None = None

    children: list[AnyItem] | None = None


@dataclass
class File(AnyIncludedItem):
    """File item in an NCDU export."""

    type: int = ItemType.File


@dataclass
class _OtherFile(AnyIncludedItem, abc.ABC):
    """Anything above a file.

    The documentation claims these fields are only available on hard links but I've
    found them to be present on some non-regular files as well.
    """

    ino: int = 0
    nlink: int = 0


@dataclass
class NonRegularFile(_OtherFile):
    """Non-regular file item in an NCDU export."""

    type: int = ItemType.NonRegularFile


@dataclass
class Hardlink(_OtherFile):
    """Hardlink (candidate) item in an NCDU export."""

    type: int = ItemType.Hardlink


item_type_map = {
    ItemType.ExcludedWithKernFS: ExcludedWithKernFS,
    ItemType.ExcludeWithX: ExcludedWithX,
    ItemType.ExcludedByPattern: ExcludedByPattern,
    ItemType.ErrorWhileReadingEntry: ErrorWhileReadingEntry,
    ItemType.Directory: Directory,
    ItemType.File: File,
    ItemType.NonRegularFile: NonRegularFile,
    ItemType.Hardlink: Hardlink,
}


def parse_ncdu(path: str | os.PathLike[str], depth: int = -1) -> Directory:
    """Parse an NCDU export.

    Args:
        path: Path to the NCDU export.
        depth: Depth at which to stop parsing the tree. Use -1 to parse the whole tree.

    Returns:
        The full file system tree.

    Raises:
        ParsingError: File failed to parse.
    """  # noqa: DOC502
    path = pathlib.Path(path)
    try:
        with path.open("rb") as handle:
            ensure_magic_bytes(handle)
            return parse_ncdu_stream(handle, depth=depth)
    except ParsingError as e:
        # Re-raise with path information
        raise e.__class__(reason=e.reason, path=path) from None


def parse_ncdu_stream(stream: BinaryIO, depth: int = -1) -> Directory:
    """Parse a binary stream from an NCDU export.

    Args:
        stream: Binary stream with NCDU data.
        depth: Depth at which to stop parsing the tree. Use -1 to parse the whole tree.

    Returns:
        The full file system tree.
    """
    # Jump to the end to get the index block
    _ = stream.seek(0, os.SEEK_END)

    index_block = read_block(stream, backwards=True)
    index_block = IndexBlock.from_bytes(index_block.content)

    return parse_tree(stream, index_block, depth)


def parse_tree(stream: BinaryIO, index_block: IndexBlock, depth: int = -1) -> Directory:
    """Parse a file system tree from a stream.

    Args:
        stream: NCDU export stream.
        index_block: Index block with data block pointers.
        depth: Depth at which to stop parsing the tree. Use -1 to parse the whole tree.

    Returns:
        The root item from the tree.

    Raises:
        NCDUError: Root item is not a directory.
    """
    data_blocks: dict[int, DataBlock] = {}

    # Jump to the block containing the root item
    block_pointer = index_block.pointers[index_block.root_reference.block_index]
    _ = stream.seek(block_pointer.offset)

    # Parse the root item's block
    root_block = read_block(stream)
    root_block = DataBlock.from_bytes(root_block.content)

    data_blocks[index_block.root_reference.block_index] = root_block

    # Parse the root item
    root_item = read_item(data_blocks, index_block.root_reference)
    if not isinstance(root_item, Directory):
        raise NCDUError("Root item is not a directory.")
    return parse_sub_tree(root_item, stream, data_blocks, index_block, depth)


def parse_sub_tree(
    root: Directory,
    stream: BinaryIO,
    blocks: dict[int, DataBlock],
    index: IndexBlock,
    depth: int = -1,
) -> Directory:
    """Parse a directory and its children.

    Args:
        root: Directory to parse.
        stream: NCDU export stream.
        blocks: Data blocks already parsed.
        index: Index block for the export.
        depth: Depth at which to stop parsing the tree. Use -1 to parse the whole tree.

    Returns:
        The root node with the full sub-tree parsed.
    """
    if depth == 0:
        return root

    children: list[AnyItem] = []

    previous: AnyItem = root
    reference: ReferenceType | None = root.sub
    while reference is not None:
        # Get an absolute reference
        if isinstance(reference, RelativeReference):
            reference = make_absolute(reference, previous.reference)

        # Retrieve or parse the block
        block = blocks.get(reference.block_index)
        if block is None:
            _ = stream.seek(index.pointers[reference.block_index].offset)
            block = read_block(stream)
            block = DataBlock.from_bytes(block.content)
            blocks[reference.block_index] = block

        # Read the referenced item
        current = read_item(blocks, reference)

        # Continue using depth-first search for children directories
        if isinstance(current, Directory):
            current = parse_sub_tree(current, stream, blocks, index, depth - 1)
        children.append(current)

        previous = current
        reference = current.prev

    root.children = children
    return root


def read_item(blocks: dict[int, DataBlock], reference: AbsoluteReference) -> AnyItem:
    """Read and parse an item with the given reference.

    Args:
        blocks: Data blocks.
        reference: Absolute item reference to the item to parse.

    Returns:
        The parsed item.

    Raises:
        NCDUError: Reference points to a block no provided.
    """
    block = blocks.get(reference.block_index)
    if block is None:
        raise NCDUError("Tried reading item with a reference to an unknown data block.")

    raw_item_bytes = iter(block.data[reference.offset :])
    item_map = read_cbor(raw_item_bytes)

    return parse_item_from_map(item_map, reference)


def parse_item_from_map(map_: CBORMap, reference: AbsoluteReference) -> AnyItem:
    """Parse a naive item map to a full item model.

    Args:
        map_: Naive, not-yet-validated map.
        reference: Absolute item reference to the item.

    Returns:
        A parse item from the map.

    Raises:
        NCDUError: A required field is missing.
        NCDUError: A field has the wrong type.
    """
    # Ensure required fields
    for field in {ItemField.TYPE, ItemField.NAME}:
        if field not in map_:
            raise NCDUError(f"Item missing {field.name.lower()} field.")

    # Validate type
    type_ = map_[ItemField.TYPE.value]
    if not isinstance(type_, int) or isinstance(type_, bool):
        raise NCDUError("Item type is not an integer.")
    type_ = type_ if type_ < ItemType.Hardlink else ItemType.NonRegularFile
    type_ = type_ if type_ > ItemType.ExcludedWithKernFS else ItemType.ExcludedByPattern
    type_ = ItemType(type_)

    # Parse map
    intermediate_map: dict[str, str | int | bool | ReferenceType | None] = {
        "name": map_.get(ItemField.NAME),
        "prev": map_.get(ItemField.PREV),
        "asize": map_.get(ItemField.ASIZE),
        "dsize": map_.get(ItemField.DSIZE),
        "dev": map_.get(ItemField.DEV),
        "rderr": map_.get(ItemField.RDERR),
        "cumasize": map_.get(ItemField.CUMASIZE),
        "cumdsize": map_.get(ItemField.CUMDSIZE),
        "shrasize": map_.get(ItemField.SHRASIZE),
        "shrdsize": map_.get(ItemField.SHRDSIZE),
        "items": map_.get(ItemField.ITEMS),
        "sub": map_.get(ItemField.SUB),
        "ino": map_.get(ItemField.INO),
        "nlink": map_.get(ItemField.NLINK),
        "uid": map_.get(ItemField.UID),
        "gid": map_.get(ItemField.GID),
        "mode": map_.get(ItemField.MODE),
        "reference": reference,
    }
    for name in ("prev", "sub"):
        value = cast("int | None", intermediate_map[name])
        intermediate_map[name] = value if value is None else make_reference(value)
    parsed_map: dict[str, str | int | bool | ReferenceType] = {
        key: value for key, value in intermediate_map.items() if value is not None
    }

    # Get item constructor
    item_type = item_type_map.get(type_)
    if item_type is None:
        raise NCDUError(f"Unsupported item type '{type_.name}'")

    return item_type(**parsed_map)  # pyright: ignore[reportArgumentType]


def read_block(stream: BinaryIO, *, backwards: bool = False) -> Block:
    """Read an NCDU block from a stream.

    Args:
        stream: Stream positioned right before or right after the block to read.
        backwards: Whether to read the block before the current stream position.

    Returns:
        A tuple of an integer indicating the block type and of the block content.
    """
    # Seek before TypeLen
    if backwards:
        _ = stream.seek(-4, os.SEEK_CUR)

    # Read TypeLen
    type_len = stream.read(4)
    type_len = int.from_bytes(type_len, byteorder="big", signed=False)

    # Split into type and length
    type_ = type_len >> 28  # High 4 bits
    length = type_len & ((0b1 << 28) - 1)  # Low 28 bits

    # Seek to the start of the block
    if backwards:
        _ = stream.seek(-(length - 4), os.SEEK_CUR)

    # Read the content
    content = stream.read(length - 8)

    # Move the stream position to after the block
    _ = stream.read(4)

    # Build the block
    return Block(type=type_, length=length, content=content)


def make_reference(value: int) -> ReferenceType:
    """Make a reference from an integer.

    Args:
        value: Value to parse as a reference.

    Returns:
        A reference parsed from the integer.
    """
    if value < 0:
        return RelativeReference.from_int(value)
    return AbsoluteReference.from_int(value)


def make_absolute(
    reference: RelativeReference, absolute: AbsoluteReference
) -> AbsoluteReference:
    """Make a relative reference absolute.

    Args:
        reference: Relative reference.
        absolute: Absolute reference the relative reference references.

    Returns:
        An absolute reference corresponding to the relative reference.
    """
    offset = absolute.offset + reference.offset

    return AbsoluteReference(block_index=absolute.block_index, offset=offset)


def ensure_magic_bytes(stream: BinaryIO) -> None:
    """Ensure a stream starts with the appropriate NCDU magic bytes.

    Args:
        stream: NCDU stream.

    Raises:
        NCDUError: File does not have the appropriate magic bytes.
    """
    if (magic_bytes := stream.read(8)) != NCDU_MAGIC_BYTES:
        raise NCDUError(f"Invalid magic bytes '{magic_bytes:X}'.")
